import sqlalchemy as sa
from sqlalchemy.orm import relationship
from .db import Base
from datetime import datetime


class Material(Base):
    __tablename__ = "materials"

    id = sa.Column(sa.String, primary_key=True, index=True)  # e.g. "mat_xxx"
    type = sa.Column(sa.String, nullable=False)  # text,pdf,doc,docx,file
    status = sa.Column(sa.String, nullable=False, default="available")

    # keep bytes out of DB, stays NULL.
    storage_url = sa.Column(sa.String, nullable=True)

    # JSON string with structured metadata
    metadata_json = sa.Column(sa.Text, nullable=True)

    filename = sa.Column(sa.String, nullable=True)
    mime = sa.Column(sa.String, nullable=True)
    sizebyte = sa.Column(sa.Integer, nullable=True)
    contentbytes = sa.Column(sa.LargeBinary, nullable=True)

    # Creation timestamp generated by DB.
    created = sa.Column(sa.DateTime(timezone=True), server_default=sa.func.now())


# 新增：User 模型
class User(Base):
    __tablename__ = "users"

    id = sa.Column(sa.String, primary_key=True, index=True)  # e.g. "user_xxx"
    email = sa.Column(sa.String, unique=True, nullable=False, index=True)
    username = sa.Column(sa.String, unique=True, nullable=False, index=True)
    password_hash = sa.Column(sa.String, nullable=False)  # bcrypt hashed password

    # Timestamps
    created_at = sa.Column(sa.DateTime, default=datetime.utcnow)
    last_login = sa.Column(sa.DateTime, nullable=True)

    # Relationship to frameworks
    frameworks = relationship(
        "Framework", back_populates="creator", cascade="all, delete-orphan"
    )


# 新增：Framework 模型
class Framework(Base):
    __tablename__ = "frameworks"

    id = sa.Column(sa.String, primary_key=True, index=True)  # e.g. "fw_xxx"
    title = sa.Column(sa.String, nullable=False)
    version = sa.Column(sa.String, default="1.0.0")
    family = sa.Column(sa.String, nullable=False, index=True)  # Group名称（AI自动分配）
    confidence = sa.Column(sa.Float, default=0.0)  # 0-100 (目前mock，未来AI计算)
    pov = sa.Column(sa.String, nullable=True)

    # User relationship
    creator_id = sa.Column(
        sa.String, sa.ForeignKey("users.id"), nullable=False, index=True
    )
    creator = relationship("User", back_populates="frameworks")

    # Framework content stored as JSON strings
    # 这样设计是为了灵活性，避免频繁修改数据库schema
    metadata_json = sa.Column(
        sa.Text, nullable=False
    )  # {title, version, tags, lastUpdated}
    steps_json = sa.Column(
        sa.Text, nullable=False
    )  # [{id, name, description, subSteps}]
    artefacts_json = sa.Column(
        sa.Text, nullable=False
    )  # {default: {...}, additional: [...]}
    risks_json = sa.Column(sa.Text, nullable=False)  # [{id, title, description}]
    escalation_json = sa.Column(sa.Text, nullable=False)  # [{id, trigger, action}]

    # Raw LLM output (for debugging and future improvements)
    raw_framework_json = sa.Column(sa.Text, nullable=True)  # 完整的AI返回
    raw_metadata_json = sa.Column(sa.Text, nullable=True)  # Local LLM提取的metadata

    # Timestamps
    created_at = sa.Column(sa.DateTime, default=datetime.utcnow, index=True)
    updated_at = sa.Column(
        sa.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )


# 预设的 Framework Groups（AI 从中选择）
FRAMEWORK_GROUPS = [
    "Financial",  # 金融、财务、投资
    "Healthcare",  # 医疗、健康
    "Legal",  # 法律、合规
    "Technology",  # 技术、IT、软件
    "Education",  # 教育、培训
    "Marketing",  # 营销、广告
    "Operations",  # 运营、流程
    "Human Resources",  # 人力资源
    "Sales",  # 销售
    "Other",  # 其他（兜底分类）
]
